[package]
name = "solix"
version = "2.2.0"
description = "Configure seu Linux de forma simples e rápida"
authors = ["Rafael do Carmo Costa"]
edition = "2021"

[lib]
name = "solix_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "process", "rt", "macros"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
sha2 = "0.10"
hex = "0.4"
tempfile = "3"
futures-util = "0.3"
